<?php

namespace GoMobility\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExperiencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperiencesRepository extends EntityRepository 
{
    /**
     * Renvoit les dernières experience ayant pour status publié
     * @param  $nbExperiences
     * @return $experiences
     */
    public function getLastExperiences($nbExperiences)
    {
        $q = $this->_em->createQueryBuilder()
            ->select('experiences')
            ->from('GoMobilitySiteBundle:Experiences','experiences')
            ->where('experiences.publish = 1')
            ->add('orderBy', 'experiences.id ASC')
            ->getQuery();
        ;
 
        $q->setFirstResult(0)
            ->setMaxResults($nbExperiences);
    
        return $q->getResult();
    }
}
