<?php

namespace GoMobility\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ExperiencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperiencesRepository extends EntityRepository 
{
    /**
     * Renvoit la pagination pour les experiences
     *
     * @param  int    $page
     * @param  int    $maxperpage
     * @param  string $sortby
     * @return Paginator
     */
    public function getList($page=1, $maxperpage=2)
    {
        $q = $this->_em->createQueryBuilder()
            ->select('experiences')
            ->from('GoMobilitySiteBundle:Experiences','experiences')
            ->where('experiences.publish = 1')
        ;
 
        $q->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);
 
        return new Paginator($q);
    }

    /**
     * Renvoit les dernières experience ayant pour status publié
     * @param  $nbExperiences
     * @return $experiences
     */
    public function getLastExperiences($nbExperiences)
    {
        $q = $this->_em->createQueryBuilder()
            ->select('experiences')
            ->from('GoMobilitySiteBundle:Experiences','experiences')
            ->where('experiences.publish = 1')
            ->add('orderBy', 'experiences.id ASC')
            ->getQuery();
        ;
 
        $q->setFirstResult(0)
            ->setMaxResults($nbExperiences);
    
        return $q->getResult();
    }

    /**
     * Renvoit la meilleur experience pour le type de transport demmandé
     * @param  $transport
     * @return $experiences
     */
    public function getBestExperienceByTransport($transport)
    {
        $q = $this->_em->createQueryBuilder()
            ->select('experiences')
            ->from('GoMobilitySiteBundle:Experiences','experiences')
            ->where('experiences.transport = :transport')
            ->setParameter('transport', $transport)
            ->add('orderBy', 'experiences.ges DESC')
            ->getQuery()
        ;
    
        $q->setMaxResults(1);
    
        return $q->getResult();
    }
}
