<?php

namespace GoMobility\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExperiencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperiencesRepository extends EntityRepository
{
}
