#MainController
go_mobility_site_homepage:
    path:     /
    defaults: { _controller: GoMobilitySiteBundle:Main:index }

go_mobility_site_projet:
    path:     /le-projet
    defaults: { _controller: GoMobilitySiteBundle:Main:projet }

#ExperienceController
go_mobility_site_experiences_register:
    path:     /vos-experiences/creer
    defaults: { _controller: GoMobilitySiteBundle:Experiences:experienceRegister }

go_mobility_site_experiences:
    path:     /vos-experiences/{page}
    defaults: { _controller: GoMobilitySiteBundle:Experiences:experiences, page:1 }

go_mobility_site_experience:
    path:     /vos-experiences/experience/{id}
    defaults: { _controller: GoMobilitySiteBundle:Experiences:experience }

go_mobility_site_experiences_create:
    path:     /experience-save
    defaults: { _controller: GoMobilitySiteBundle:Experiences:experienceCreate }

#BlogController
go_mobility_site_actualites:
    path: /actualites/{page}
    defaults: { _controller: GoMobilitySiteBundle:Blog:actualites, page:1 }

go_mobility_site_actualite:
    path: /actualite/{id}
    defaults: { _controller: GoMobilitySiteBundle:Blog:actualite }