go_mobility_admin:
    resource: "@GoMobilityAdminBundle/Resources/config/routing.yml"
    prefix:   /

go_mobility_site:
    resource: "@GoMobilitySiteBundle/Resources/config/routing.yml"
    prefix:   /

