parameters:
#    go_mobility_comment.example.class: GoMobility\CommentBundle\Example

services:
#    go_mobility_comment.example:
#        class: %go_mobility_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
