#Main Controller
go_mobility_admin_homepage:
    path:     /admin
    defaults: { _controller: GoMobilityAdminBundle:Main:index }

#Acteurs Controller
go_mobility_admin_acteurs:
    path:     /admin/eco-acteurs
    defaults: { _controller: GoMobilityAdminBundle:Actors:index }

go_mobility_admin_acteur:
    path:     /admin/eco-acteurs/{id}
    defaults: { _controller: GoMobilityAdminBundle:Actors:show }

go_mobility_admin_acteur_update:
    path:     /admin/eco-acteurs/update/{id}
    defaults: { _controller: GoMobilityAdminBundle:Actors:update }


#Comments Controller
go_mobility_admin_comments:
    path:     /admin/commentaires
    defaults: { _controller: GoMobilityAdminBundle:Comments:index }    

#Public Controller
go_mobility_admin_public:
    path:     /admin/public
    defaults: { _controller: GoMobilityAdminBundle:Public:index }

go_mobility_admin_public_create:
    path:     /admin/public/creer
    defaults: { _controller: GoMobilityAdminBundle:Public:create }

go_mobility_admin_public_save:
    path:     /admin/public/sauvegarder
    defaults: { _controller: GoMobilityAdminBundle:Public:save }
